name: SSH to GitHub Actions
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection to Actions
      uses: yi985432/ssh2actions@main
      run: |
         sleep 20000
